In [1]:
import pandas as pd

from lib.utils import get_65min_aggs

In [2]:
data = pd.read_csv('/Users/beneverman/Documents/Coding/QuantHive/IDVF-Oxford-v1/data/processed-5yr-93-minute/65min_rv.csv', index_col=0)

In [7]:
data2 = get_65min_aggs()

In [11]:
data

,datetime,TMO,ABT,HD,MCD,PG,CAT,DIS,CCI,JNJ,...,COST,IBM,ADP,AVGO,WMT,AMGN,INTU,AXP,MMC,CB
0,2018-10-11 10:35:00-04:00,-9.302132,-9.308770,-8.861162,-9.032787,-9.181782,-8.267610,-8.949561,-9.245858,-9.123982,...,-9.758462,-9.029469,-9.164025,-7.821013,-9.906052,-8.309061,-7.986252,-8.662172,-9.824389,-9.117123
1,2018-10-11 11:40:00-04:00,-9.226515,-9.660382,-9.765163,-10.027525,-10.502906,-8.801236,-10.125150,-10.421172,-10.023504,...,-10.126290,-9.864239,-9.209012,-8.637280,-10.469171,-9.083652,-8.634823,-9.688864,-10.128361,-9.916038
2,2018-10-11 12:45:00-04:00,-9.818327,-10.029960,-10.518059,-10.743978,-10.994644,-9.591604,-10.272350,-10.747697,-10.491507,...,-10.732626,-10.336389,-9.891691,-9.291962,-10.898001,-9.966830,-9.518611,-10.129218,-10.798520,-10.359858
3,2018-10-11 13:50:00-04:00,-10.207846,-10.672297,-10.974280,-11.049742,-11.168651,-9.828537,-10.841925,-11.778167,-10.952831,...,-10.943079,-10.542780,-10.012840,-9.699978,-11.319553,-10.194840,-9.536182,-10.620143,-11.741473,-10.880489
4,2018-10-11 14:55:00-04:00,-8.921766,-8.968561,-8.872568,-9.690731,-9.740425,-8.682480,-9.503440,-10.269008,-9.185082,...,-9.973373,-9.243132,-9.060507,-8.967603,-9.951001,-9.123352,-8.827453,-9.273452,-9.856659,-9.745645
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7511,2023-10-09 11:40:00-04:00,-10.733918,-11.561414,-11.459266,-11.630080,-11.549440,-10.420834,-10.661230,-11.052822,-11.640935,...,-10.752899,-11.384324,-11.297519,-10.206596,-11.178907,-10.680779,-10.645832,-10.627294,-11.829896,-11.312079
7512,2023-10-09 12:45:00-04:00,-11.575774,-11.660044,-11.389878,-11.992928,-11.837725,-10.662594,-11.225769,-9.910547,-12.022989,...,-10.925418,-12.035542,-12.237446,-11.091774,-11.439434,-11.202431,-11.457626,-11.228341,-11.642755,-11.378411
7513,2023-10-09 13:50:00-04:00,-11.869460,-11.628670,-11.684992,-11.961455,-11.665920,-10.952734,-11.278099,-10.838116,-12.250040,...,-11.705529,-12.087832,-11.997735,-10.649890,-11.542805,-11.382209,-11.012721,-11.832090,-11.737761,-11.501302
7514,2023-10-09 14:55:00-04:00,-11.277812,-11.982515,-11.641741,-12.104332,-12.100556,-11.159378,-11.756749,-11.311528,-12.244460,...,-11.609444,-12.312214,-12.193028,-10.515182,-11.398901,-11.671222,-11.120266,-11.961500,-12.197529,-11.755987
7515,2023-10-09 16:00:00-04:00,-11.655459,-11.975486,-11.603576,-11.875128,-12.236133,-11.042433,-11.301144,-10.657317,-12.174962,...,-11.556200,-12.348149,-11.806256,-10.442070,-11.731128,-12.157248,-11.144227,-11.330272,-12.216797,-11.786497

In [10]:
data2

,datetime,TMO,ABT,HD,MCD,PG,CAT,DIS,CCI,JNJ,...,COST,IBM,ADP,AVGO,WMT,AMGN,INTU,AXP,MMC,CB
0,2018-10-11 09:30:00-04:00,231.4025,68.9400,195.260,165.720,80.680,143.9900,112.295,107.9300,136.72,...,223.6400,142.6300,140.5400,235.2900,95.3400,196.330,206.100,103.690,81.180,130.04
1,2018-10-11 10:35:00-04:00,228.4800,68.6200,193.320,164.405,80.185,142.7600,111.960,107.0100,135.64,...,222.7690,141.5762,139.3662,232.7200,95.0200,195.780,204.730,103.000,80.960,128.15
2,2018-10-11 11:40:00-04:00,231.4800,69.3857,194.630,164.970,79.970,143.6000,112.580,107.0700,136.26,...,225.2500,142.2400,140.4100,233.8500,95.1000,197.770,205.390,103.660,81.130,128.42
3,2018-10-11 12:45:00-04:00,228.9800,68.8200,193.570,164.150,79.660,142.8800,112.190,106.7900,135.87,...,224.3500,141.3201,139.6500,232.5700,94.9400,195.720,203.990,103.330,80.870,127.92
4,2018-10-11 13:50:00-04:00,226.8900,68.3500,190.040,162.850,79.210,141.8500,111.200,105.3590,134.41,...,222.2557,139.9300,138.4400,229.4200,94.1500,194.650,201.700,102.280,79.980,126.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7511,2023-10-09 10:35:00-04:00,492.3400,96.0800,291.235,248.350,141.960,267.2700,83.895,92.6000,157.94,...,552.4000,141.2300,248.2800,842.9400,153.9400,271.065,529.726,149.035,192.720,210.19
7512,2023-10-09 11:40:00-04:00,492.7300,95.8850,292.350,247.935,142.340,267.8525,83.990,92.7200,157.58,...,554.6400,141.0100,248.2700,845.7300,154.1828,269.490,530.270,148.530,192.580,209.00
7513,2023-10-09 12:45:00-04:00,494.6027,96.4200,294.245,249.410,142.935,270.1700,84.515,93.3179,158.23,...,556.8100,141.7500,249.3700,853.2500,154.8300,271.390,533.900,149.050,193.005,209.89
7514,2023-10-09 13:50:00-04:00,497.1050,96.7100,295.300,249.300,143.010,271.0400,84.735,93.3600,158.35,...,558.5200,142.0152,250.0100,854.1507,155.4100,271.590,534.700,149.255,193.440,210.18
7515,2023-10-09 14:55:00-04:00,496.0900,96.7600,295.360,249.950,143.360,271.1600,84.700,93.1800,158.54,...,558.9300,142.1900,250.2300,855.9500,155.8400,271.590,535.110,148.870,193.090,210.49

In [7]:
result = pd.read_csv("/Users/beneverman/Documents/Coding/QuantHive/IDVF-Oxford-v1/outputs/linear-as-close-as-possible-v2/2023-10-16_20-12-20/result.csv", index_col=0)
report = pd.read_csv("/Users/beneverman/Documents/Coding/QuantHive/IDVF-Oxford-v1/outputs/linear-as-close-as-possible-v2/2023-10-16_20-12-20/report.csv", index_col=0)

In [8]:
report.describe()

             MSE   r2_score       MAPE
count  93.000000  93.000000  93.000000
mean    0.253814   0.698717   0.035898
std     0.023867   0.022873   0.002408
min     0.188770   0.640770   0.030049
25%     0.242645   0.680533   0.034555
50%     0.253372   0.700198   0.035682
75%     0.269451   0.714535   0.037332
max     0.310789   0.745395   0.042423